{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "crispy_crust = 0\n",
    "cart = []\n",
    "price = 0\n",
    "order = []  \n",
    "\n",
    "while crispy_crust != 4:\n",
    "    crispy_crust = int(input(\" 1- Menu \\n 2- Cart \\n 3- My Orders \\n 4- Exit \\n Enter your choice: \"))\n",
    "    print(\"\")\n",
    "    \n",
    "    if crispy_crust == 1:\n",
    "        menu = int(input(\"Menu \\n 1- Premium Deals \\n 2- Burgers \\n 3- Pasta \\n 0- Back \\n Enter one of the above choices: \"))\n",
    "        print(\"\")\n",
    "        \n",
    "        if menu == 1:\n",
    "            premium_deals = \"\"\n",
    "            while premium_deals != 7:\n",
    "                premium_deals = int(input(\" 1- Premium deal 1 \\n 1 Legend Pizza (Medium), 6 Chicken Wings & 1 Litre Soft Drink \\t Rs: 1820.00 \\n \\n\" +\n",
    "                                          \" 2- Premium deal 2 \\n 2 Legend Pizzas (Medium) & 1.5 Litre Soft Drink \\t Rs: 2470.00 \\n \\n\" +\n",
    "                                          \" 3- Premium deal 3 \\n 1 Legend Pizza (Large), Any Pasta & 1.5 Litre Soft Drink \\t Rs: 2510.00 \\n \\n\" +\n",
    "                                          \" 4- Premium deal 4 \\n 1 Legend Pizza (Party), 12 Chicken Wings & 1.5 Litre Soft Drink \\t Rs: 3620.00 \\n \\n\" + \n",
    "                                          \" 5- Premium deal 5 \\n 2 Legend Pizzas (Large) & 1.5 Litre Soft Drink \\t Rs: 3310.00 \\n \\n\" +\n",
    "                                          \" 6- Premium deal 6 \\n 1 Legend Pizza (Large), 1 Ultimate Pizza (Large) & 1.5 Litre Soft Drink \\t Rs: 3500.00 \\n \\n\" +  \n",
    "                                          \" 7- Back \\n \\n\"\n",
    "                                          \"Enter your choice: \"))\n",
    "                print(\"\")\n",
    "                \n",
    "                if 1 <= premium_deals <= 6:  # Adjusted the condition\n",
    "                    add_to_cart = int(input(\"Are you sure you want to add to cart \\n 1- Yes \\t 2- No \\n Enter your choice: \"))\n",
    "                    if add_to_cart == 1:\n",
    "                        cart.append(f\"Premium deal {premium_deals}\")\n",
    "                        if premium_deals == 1:\n",
    "                            price += 1820\n",
    "                        elif premium_deals == 2:\n",
    "                            price += 2470\n",
    "                        elif premium_deals == 3:\n",
    "                            price += 2510\n",
    "                        elif premium_deals == 4:\n",
    "                            price += 3620\n",
    "                        elif premium_deals == 5:\n",
    "                            price += 3310\n",
    "                        elif premium_deals == 6:\n",
    "                            price += 3500\n",
    "                        print(\"Item added to cart.\")\n",
    "                \n",
    "        elif menu == 2:\n",
    "            burgers = \"\"\n",
    "            while burgers != 4:\n",
    "                burgers = int(input(\" 1- Buzz Burger \\t Rs.390.00 \\n \\n\" +\n",
    "                                    \" 2- Crispy Zinger Burger \\t Rs. 530.00 \\n \\n\" +\n",
    "                                    \" 3- Double Decker Burger \\t Rs. 730.00 \\n \\n\" +\n",
    "                                    \" 4- Back \\n \\n\" +\n",
    "                                    \" Enter your choice: \"))\n",
    "                print(\"\")\n",
    "                \n",
    "                if 1 <= burgers <= 3:  # Adjusted the condition\n",
    "                    add_to_cart = int(input(\"Are you sure you want to add to cart \\n 1- Yes \\t 2- No \\n Enter your choice: \"))\n",
    "                    if add_to_cart == 1:\n",
    "                        if burgers == 1:\n",
    "                            cart.append(\"Buzz Burger\")\n",
    "                            price += 390\n",
    "                        elif burgers == 2:\n",
    "                            cart.append(\"Crispy Zinger Burger\")\n",
    "                            price += 530\n",
    "                        elif burgers == 3:\n",
    "                            cart.append(\"Double Decker Burger\")\n",
    "                            price += 730\n",
    "                        print(\"Item added to cart.\")\n",
    "        \n",
    "        elif menu == 3:\n",
    "            pasta = \"\"\n",
    "            while pasta != 3:\n",
    "                pasta = int(input(\" 1- Creamy Alfredo Pasta \\t Rs. 550.00 \\n \\n\" +\n",
    "                                  \" 2- Crunchy Chicken Pasta \\t Rs. 500.00 \\n \\n\" +\n",
    "                                  \" 3- Back \\n \\n\" +\n",
    "                                  \" Enter your choice: \"))\n",
    "                print(\"\")\n",
    "                \n",
    "                if 1 <= pasta <= 2:  # Adjusted the condition\n",
    "                    add_to_cart = int(input(\"Are you sure you want to add to cart \\n 1- Yes \\t 2- No \\n Enter your choice: \"))\n",
    "                    if add_to_cart == 1:\n",
    "                        if pasta == 1:\n",
    "                            cart.append(\"Creamy Alfredo Pasta\")\n",
    "                            price += 550\n",
    "                        elif pasta == 2:\n",
    "                            cart.append(\"Crunchy Chicken Pasta\")\n",
    "                            price += 500\n",
    "                        print(\"Item added to cart.\")\n",
    "    \n",
    "    elif crispy_crust == 2:\n",
    "        print(\"Your items in cart \")\n",
    "        for items in cart:\n",
    "            print(items)\n",
    "        print(\"Total bill: Rs. \", price)\n",
    "        print(\"\")\n",
    "        \n",
    "        choice = int(input(\" 1- Checkout \\n 2- Back \\n Enter your choice: \"))\n",
    "        if choice == 1:\n",
    "            print(\"Do you want to checkout now: \\n 1- Yes \\t 2- No\")\n",
    "            checkout = int(input(\"Enter your choice: \"))    \n",
    "            if checkout == 1:\n",
    "                payment = int(input(\" Select Payment Method \\n \\n\" +\n",
    "                                    \" 1- Credit\\\\Debit card \\n\" +\n",
    "                                    \" 2- Cash on delivery \\n\" +\n",
    "                                    \" Enter your choice: \"))\n",
    "                if payment == 1:\n",
    "                    card_number = int(input(\"Enter your card number: \"))\n",
    "                    card_passcode = int(input(\"Enter your card's passcode: \"))\n",
    "                    address = input(\"Enter your address: \")\n",
    "                    print(\"\")\n",
    "                    place_order = int(input(\"Do you want to checkout now: \\n 1- Yes \\t 2- No \\n Enter your choice: \"))\n",
    "                    if place_order == 1:\n",
    "                        order = cart\n",
    "                        print(\"Your order has been placed successfully. Thanks for choosing Crispy Crust.\")\n",
    "                    else:\n",
    "                        print(\"No order placed.\")\n",
    "                elif payment == 2:\n",
    "                    address = input(\"Enter your address: \")\n",
    "                    print(\"\")\n",
    "                    place_order = int(input(\"Do you want to checkout now: \\n 1- Yes \\t 2- No \\n Enter your choice: \"))\n",
    "                    if place_order == 1:\n",
    "                        order = cart\n",
    "                        print(\"Your order has been placed successfully. Please keep your cash ready. Thanks for choosing Crispy Crust.\")\n",
    "                    else:\n",
    "                        print(\"No order placed.\")\n",
    "    \n",
    "    elif crispy_crust == 3:\n",
    "        print(\"Your Orders\")\n",
    "        for items in order:\n",
    "            print(items)\n",
    "            print(\"\")\n",
    "    \n",
    "    elif crispy_crust == 4:\n",
    "        print(\"Thanks  For Visiting Crispy Crust.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
